services:
  db:
    image: mariadb:10.6
    container_name: demo-db
    environment:
      MYSQL_ROOT_PASSWORD: Root1234*
      MYSQL_DATABASE: rrhh
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pRoot1234*"]
      interval: 10s
      timeout: 5s
      retries: 5
 volumes:
  - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: demo-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/rrhh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root1234*
